# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    '{develop,master}':
    - step:
        name: Run tests
        caches:
          - node
        script:
          - cd web
          - npm install
          - npm rebuild node-sass
          - npm run build --prod
    master:
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - echo "Deploying to test environment"