# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.14.1

definitions:
  caches:
    angular-modules: web/node_modules
  steps:
    - step: &Test-step
        name: Run tests
        caches:
          - angular-modules
        script:
          - cd web
          - npm install
          - npm rebuild node-sass
          - npm run build -- --prod
    - step: &Deploydev-step
        name: Deploy to staging
        deployment: staging
        script:
          - echo "Deploying to test environment"
          - pipe: atlassian/ssh-run:0.2.4
            variables:
              SSH_USER: $SSH_DEVELOP_USER
              SERVER: $SHH_DEVELOP_SERVER
              COMMAND: '~/repos/restart_proyect template4.0 template'
    - step: &Deploy-step
        name: Deploy to production
        deployment: production
        script:
          - echo "Deploying to test environment"
          - pipe: atlassian/ssh-run:0.2.4
            variables:
              SSH_USER: $SSH_DEVELOP_USER
              SERVER: $SHH_DEVELOP_SERVER
              COMMAND: '~/repos/template4.0/deploy-script-develop.sh'


pipelines:
  branches:
    develop:
      - step: *Test-step
      - step: *Deploydev-step
    master:
      - step: *Test-step
      #- step: *Deploy-step