FROM node:8.12-alpine

# Set Enviroment
# COPY . /app
VOLUME [ "/app" ]
WORKDIR /app

# Install angular CLI
RUN npm install -g @angular/cli

# Install app dependencies
# RUN npm install

# Expose the listening port of your app
EXPOSE 4200